---
### General Information ###
info:
  app:
    name: Redis Service Broker
    description: Redis Service Broker for Cloud Foundry Service Deployments
    version: 1.2.0

spring:
  profiles: default
  ### General Information ###
  application:
      name: cf-service-broker-redis
  ### Security ###
  ssl:
    acceptselfsigned: true
  ### Cloud Config ###
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8081}

server:
  port: ${SERVER_PORT:8080}

### Logging ###
logging:
  file: ${LOG_FILE:cf-service-broker-redis.log}
  level:
    root: ${LOG_LEVEL_ROOT:INFO}