---
# https://bosh.io/docs/cli-v2.html#deployment-mgmt

name: redis

releases:
- name: osb-bosh-redis
  version: latest

update:
  canaries: 1
  max_in_flight: 2
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

stemcells:
- alias: default
  os: ubuntu-trusty

############################################################
instance_groups:
- name: redis
  instances: 3
  azs:
  - z1
  jobs:
  - name: redis
    release: osb-bosh-redis
  vm_type: default
  stemcell: default
  persistent_disk_type: default
  networks:
  - name: default
  properties:
    redis:
      password: random123

- name: cluster-configuration
  instances: 1
  lifecycle: errand
  azs:
  - z1
  jobs:
  - name: cluster-config
    release: osb-bosh-redis
  vm_type: default
  stemcell: default
  persistent_disk_type: default
  networks:
  - name: default